version: '2.1'

services:

  mysqldb:
    image: mysql:5.7.32
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=todosdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60  

  api-service:
    image: nagabhushanamn/todos-api-service
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy  

  web-ui:
    image: nagabhushanamn/todos-web-ui
    ports:
      - "80:80"    
